config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title,:body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    current_page = (params[:page] || 1).to_i
    @articles = Article.order(created_at: :desc).page(current_page).per(2)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def month_day_year(datetime)
        datetime.strftime('%B %e, %Y')
    end

end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-body-tertiary rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
</div>

app/views/articles/_archives.html.erb
        <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">

</div>

<article class="blog-post">
    <h2 class="display-5 link-body-emphasis mb-1"><%= article.title %></h2>
    <p class="blog-post-meta"><%= month_day_year(article.created_at) %><a href="#">Chris</a></p>

    <p>
     <%= truncate(article.body, length: 150) %>
    </p>

    <p>
     <%= link_to "continue reading...", article,class:"btn btn-link"  %>
    </p>

    <div class="d-flex flex-row">

      <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-secondary"%>
     
      <%= button_to "Destroy this article", article,
      method: :delete ,
      class: "btn btn-danger"
      %>         
    </div>
</article>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |form| %>
  <%= form.input :title %>
  <%= form.input :body, input_html:{ rows: 10} %> 
 
    <%= form.button :submit, class: "btn btn-primary" %>
  
    <%= link_to "Back to articles", articles_path, class: "btn btn-secondary" %>

<% end %>

app/views/articles/_longer_feature.html.erb
<main class="container">
  <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <p class="lead mb-0"><a href="#" class="text-body-emphasis fw-bold">Continue reading...</a></p>
    </div>
  </div>

app/views/articles/_medium_feature.html.erb
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-body-secondary">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success-emphasis">Design</strong>
          <h3 class="mb-0">Post title</h3>
          <div class="mb-1 text-body-secondary">Nov 11</div>
          <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
  </div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
        <%= link_to_next_page @articles, "Older", class: "btn btn-outline-primary" %>
        <%= link_to_previous_page @articles, "Newer", class: "btn btn-outline-primary" %>


  <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>



  <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">Newer</a>




</nav>

app/views/articles/_right_side.html.erb
 <div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <%= render 'about'%>
        
        <%= render 'archives'%>

        <%= render 'elsewhere'%>
    </div>
    
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<%= render 'longer_feature'%>

<%= render 'medium_feature'%>

<div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        From the Firehose
      </h3>
    

      <p style="color: green"><%= notice %></p>

      <%= link_to "New article", new_article_path, class: "btn btn-primary" %>

      <div id="articles">
        <% @articles.each do |article| %>
          <%= render article %>
          <p>
            <%= link_to "Show this article", article %>
          </p>
        <% end %>
      </div>

      <%= render 'pagination' %>
    </div>
  <%= render 'right_side' %>

</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<div id="<%= dom_id @article %>">

</div>

<article class="blog-post">
    <h2 class="display-5 link-body-emphasis mb-1"><%= @article.title %></h2>
    <p class="blog-post-meta"><%= month_day_year(@article.created_at) %><a href="#">Chris</a></p>

      <p>
      <%= @article.body %>
      </p>

    <div class="d-flex flex-row">
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-secondary"%>
      <%= button_to "Destroy this article", @article,
      method: :delete ,
      class: "btn btn-danger"
      %>       
      <%= link_to "Back to articles", articles_path, class: "btn btn-info" %>
    </div>
</article>

app/views/layouts/_footer.html.erb
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p class="mb-0">
        <a href="#">Back to top</a>
      </p>
</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
      <header class="border-bottom lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="link-secondary" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Large</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="link-secondary" href="#" aria-label="Search">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-3 border-bottom">
        <nav class="nav nav-underline justify-content-between">
          <a class="nav-item nav-link link-body-emphasis active" href="#">World</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">U.S.</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Technology</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Design</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Culture</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Business</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Politics</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Opinion</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Science</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Health</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Style</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Travel</a>
        </nav>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDoDev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
      
  <%= render "layouts/topnavbar" %>


  <main class="container">
    <%= yield %>
  </main>

  <%= render "layouts/footer" %>

  <main class="container">

  </main>
  </body>
</html>